export const ActionNames = {
    SET_ALL_PRODUCTS: "SET_ALL_PRODUCTS",
    SET_CART_INITIAL_STATE:"SET_CART_INITIAL_STATE",
    ADD_TO_CART:"ADD_TO_CART",
    REMOVE_FROM_CART:"REMOVE_FROM_CART",
    ADD_QUANTITY:"ADD_QUANTITY",
    SUBTRACT_QUANTITY:"SUBTRACT_QUANTITY",
    SELECTED_PRODUCT_DETAILS: "SELECTED_PRODUCT_DETAILS",
    REMOVE_SELECTED_PRODUCT_DETAILS: "REMOVE_SELECTED_PRODUCT_DETAILS",
    EMPTY_THE_CART:"EMPTY_THE_CART",
    LOGIN:"LOGIN",
    LOGOUT:"LOGOUT",
    
};